params:
  # Temperature schedule
  Tmax: 20
  Tmin: 1e-6

  # Iteration counts
  nsteps: 500 # Outer temperature steps
  nsteps_per_T: 2000 # Inner steps per temperature (Total 1M steps)

  # Cooling schedule: "linear", "exponential", or "polynomial"
  cooling: "polynomial"
  alpha: 0.99
  n: 4 # Polynomial exponent (only used if cooling=polynomial)

  # Perturbation deltas
  position_delta: 0.05
  angle_delta: 15
  # Misc
  random_state: 23333
  log_freq: 100000

  # Penalty-based SA
  overlap_penalty: 20.0 # Î» multiplier for overlap area in score
